### ISSUE TITLE
/bin/sh: atom: command not found

### ISSUE THREAD

**Issue by reneruiz** [mizdra/eslint-interactive#293]
First off this tool is amazing thank you so much!

Attempting to use `makeFixableAndFix` or`applySuggestions` results in error:

```
✔ Which rules would you like to apply action? · prefer-regex-literals
✔ Which action do you want to do? · applySuggestions
Opening editor...
Error: Command failed: atom [my_path]/node_modules/.cache/eslint-interactive/10.8.0/filter-script/prefer-regex-literals.js
/bin/sh: atom: command not found

    at __node_internal_genericNodeError (node:internal/errors:857:15)
    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'atom [my_path]/node_modules/.cache/eslint-interactive/10.8.0/filter-script/prefer-regex-literals.js',
  stdout: '',
  stderr: '/bin/sh: atom: command not found\n'
}
✨  Done in 17.04s.
```

Arguments used:
`$ eslint-interactive 'src/**/*.{js,jsx}' --cache`

```
$ node -v
v16.20.1
```

**Comment by reneruiz** [comment]
Oh, I see what's happening. It's attempting to open whatever I had set as $EDITOR. Which I have in a very old dotfiles config when I used to use Atom editor.

**Comment by mizdra** [comment]
Exactly.

`makeFixableAndFix` and `applySuggestions` are actions that programmatically fix lint errors using a user script.

When these actions are executed, eslint-interactive first tries to open the userscript template file in an editor. It then edits the file in the editor, closes the editor and performs the lint error fix. If you have experience using git from the CLI, you will understand that this behaviour is similar to the way git commit commit messages are typed.

eslint-interactive will attempt to open the editor if it has `EDITOR` environment variable. For example, if `EDITOR="code --wait"` is set, vscode will be opened. If there is no `EDITOR` environment variable, it will open vim.

---


From the error message you provided, it appears that action is failing because the atom command is not installed on your system. Please try installing the atom command or configuring another editor.

**Comment by mizdra** [comment]
I think the cause of this problem is your dotfiles configuration, not eslint-interactive. I will therefore close this issue.

If the issue is not resolved, open a new issue.
