### ISSUE TITLE
`applySuggestions` hangs on "Opening editor..."

### ISSUE THREAD

**Issue by eddie-dunn** [mizdra/eslint-interactive#347]
![image](https://github.com/mizdra/eslint-interactive/assets/219063/92262b4e-113a-446c-bbad-1b373972325f)

I ran eslint-interactive via `npx`. OS is Fedora Silverblue 39.

**Comment by mizdra** [comment]
@eddie-dunn I think this is the same as #328. Could you try the solution described in the issue?

**Comment by mizdra** [comment]
Probably because eslint-interactive is using ESLint v9. ESLint v9 loads the flat config by default, not the legacy config. The .eslintrc.js is not loaded by default because it is a legacy config.

To load the legacy config, start eslint-interactive with the `ESLINT_USE_FLAT_CONFIG=false` environment variable set.

**Comment by mizdra** [comment]
Please try https://github.com/mizdra/eslint-interactive/issues/347#issuecomment-2084150296 :)
